//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class APlusItem
    {
        public int APlusItem_Id { get; set; }
        public string Itm_Num { get; set; }
        public string Item_Desc1 { get; set; }
        public string Item_Desc2 { get; set; }
        public string VendorNumber { get; set; }
        public string MFG_Number { get; set; }
        public string UPC { get; set; }
    }
}
