//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeType
    {
        public AttributeType()
        {
            this.Attribute_Lookup = new HashSet<Attribute_Lookup>();
            this.CategoryAttributes = new HashSet<CategoryAttribute>();
            this.ItemDescriptionOrders = new HashSet<ItemDescriptionOrder>();
        }
    
        public int AttributeType_Id { get; set; }
        public string AttributeType1 { get; set; }
        public Nullable<bool> Range { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Attribute_Lookup> Attribute_Lookup { get; set; }
        public virtual ICollection<CategoryAttribute> CategoryAttributes { get; set; }
        public virtual ICollection<ItemDescriptionOrder> ItemDescriptionOrders { get; set; }
    }
}
