//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute_Lookup
    {
        public Attribute_Lookup()
        {
            this.ItemAttributes = new HashSet<ItemAttribute>();
        }
    
        public int AttributeLookup_Id { get; set; }
        public int AttributeType_Id { get; set; }
        public string WebsiteAttributeValue { get; set; }
        public string APlusAttributeValue { get; set; }
        public string DefaultActualValue { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual AttributeType AttributeType { get; set; }
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
    }
}
