//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int Buyer_Id { get; set; }
        public string BuyerNumber { get; set; }
        public string BuyerName { get; set; }
        public Nullable<int> ModfiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
