//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFLType
    {
        public FFLType()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int FFLType_Id { get; set; }
        public string FFLType_Code { get; set; }
        public string FFLType_Description { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
