//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freight_Lookup
    {
        public Freight_Lookup()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Freight_Id { get; set; }
        public string Freight_APlusClass { get; set; }
        public string Freight_DotClass { get; set; }
        public string Freight_ItemClass { get; set; }
        public string Freight_Commodity { get; set; }
        public Nullable<int> Freight_NMFCItemNumber { get; set; }
        public string Freight_Hazard { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
