//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemTextAttachments = new HashSet<ItemTextAttachment>();
            this.ItemWareHouses = new HashSet<ItemWareHous>();
            this.PrintedItemsForAPlus = new HashSet<PrintedItemsForAPlu>();
            this.ItemAttributes = new HashSet<ItemAttribute>();
        }
    
        public int Item_id { get; set; }
        public string Itm_Num { get; set; }
        public Nullable<int> ManufacturerLogo_Id { get; set; }
        public string Item_Description { get; set; }
        public string APlusDescription1 { get; set; }
        public string APlusDescription2 { get; set; }
        public string MFG_Number { get; set; }
        public Nullable<int> UM_Id { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> Level1 { get; set; }
        public Nullable<decimal> Level2 { get; set; }
        public Nullable<decimal> Level3 { get; set; }
        public Nullable<decimal> JSCLevel5 { get; set; }
        public string Qty_Break { get; set; }
        public Nullable<decimal> Qty_BreakPrice { get; set; }
        public int CategoryClass_Id { get; set; }
        public Nullable<int> SubClassCode_Id { get; set; }
        public Nullable<int> FineLineCode_Id { get; set; }
        public Nullable<int> CatWebCode_Id { get; set; }
        public Nullable<int> Freight_Id { get; set; }
        public string Plan_YN { get; set; }
        public Nullable<int> ABC_Id { get; set; }
        public string DS { get; set; }
        public Nullable<int> STD { get; set; }
        public string MIN { get; set; }
        public Nullable<decimal> VICost { get; set; }
        public string Haz { get; set; }
        public string UPC { get; set; }
        public string Buyer { get; set; }
        public string Exclusive { get; set; }
        public string Allocated { get; set; }
        public string DropShip { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Approved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ReadyForApproval { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FastTrack { get; set; }
        public Nullable<int> FastTrackBy { get; set; }
        public Nullable<System.DateTime> FastTrackDate { get; set; }
        public Nullable<int> FFLType_Id { get; set; }
        public string FFLCaliber { get; set; }
        public string FFLModel { get; set; }
        public string FFLMFGName { get; set; }
        public string FFLMFGImportName { get; set; }
        public string PreventFromWeb { get; set; }
        public string SpecialOrder { get; set; }
        public string EDIUPC { get; set; }
        public string FFLGauge { get; set; }
        public string FFLLock { get; set; }
        public Nullable<System.DateTime> FFLLockDate { get; set; }
        public Nullable<decimal> MinAdvertisePrice { get; set; }
        public string WholeSaleMTP { get; set; }
        public string Printed { get; set; }
        public Nullable<int> AssignedBuyer_Id { get; set; }
        public Nullable<decimal> Level4 { get; set; }
        public string SF_Item_Description { get; set; }
        public string MinAdvertisePriceFlag { get; set; }
        public string Company99 { get; set; }
        public Nullable<int> EDIUM_id { get; set; }
        public Nullable<int> countryOrig_id { get; set; }
        public Nullable<int> countryManuf_id { get; set; }
        public Nullable<int> AltUM_id { get; set; }
        public Nullable<int> EDIUM_quantity { get; set; }
        public byte[] ItmImage { get; set; }
    
        public virtual ABC_Lookup ABC_Lookup { get; set; }
        public virtual CategoryClass CategoryClass { get; set; }
        public virtual FFLType FFLType { get; set; }
        public virtual FineLineClass FineLineClass { get; set; }
        public virtual Freight_Lookup Freight_Lookup { get; set; }
        public virtual SubClass SubClass { get; set; }
        public virtual UM_Lookup UM_Lookup { get; set; }
        public virtual WebCode WebCode { get; set; }
        public virtual zManufacturersLogo zManufacturersLogo { get; set; }
        public virtual ICollection<ItemTextAttachment> ItemTextAttachments { get; set; }
        public virtual ICollection<ItemWareHous> ItemWareHouses { get; set; }
        public virtual ICollection<PrintedItemsForAPlu> PrintedItemsForAPlus { get; set; }
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
    }
}
