//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttribute
    {
        public int ItemAttribute_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> AttributeLookup_Id { get; set; }
        public string ActualAttributeValue { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
    
        public virtual Attribute_Lookup Attribute_Lookup { get; set; }
        public virtual Item Item { get; set; }
    }
}
