//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplacementItem
    {
        public int id { get; set; }
        public int ItmId { get; set; }
        public string existingItm_Num { get; set; }
        public string replacementCode { get; set; }
        public Nullable<System.DateTime> replacementCreateDate { get; set; }
        public string importedToAPlus { get; set; }
    }
}
