//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSetup
    {
        public int id { get; set; }
        public int zManufacturersLogoId { get; set; }
        public Nullable<byte> VendorSetupType { get; set; }
        public Nullable<int> AddrId { get; set; }
        public Nullable<int> VendorContactInfoId { get; set; }
        public string ContactName { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> DiffPayee { get; set; }
        public string DiffVendorNum { get; set; }
        public string DiffVendorName { get; set; }
        public Nullable<int> DiffAddrId { get; set; }
        public Nullable<int> DiffContactInfoId { get; set; }
        public string FreightCompany { get; set; }
        public Nullable<bool> IncludeUPS { get; set; }
        public Nullable<bool> FOBOrigin { get; set; }
        public Nullable<bool> FOBDestination { get; set; }
        public string FreightTerms { get; set; }
        public string MinValue { get; set; }
        public string MinUnits { get; set; }
        public string MinWeight { get; set; }
        public string MinSize { get; set; }
        public string CO_OPPercent { get; set; }
        public string VendorLeadTime { get; set; }
        public Nullable<int> PTDscPercent { get; set; }
        public Nullable<int> PTDscDays { get; set; }
        public Nullable<int> PTPayDays { get; set; }
        public Nullable<bool> FSAUsc { get; set; }
        public Nullable<bool> CIToUsc { get; set; }
        public Nullable<bool> FFLToUsc { get; set; }
        public Nullable<bool> W9ToUsc { get; set; }
        public Nullable<bool> Hazardous { get; set; }
        public Nullable<bool> MSDS { get; set; }
        public string AcctContactName { get; set; }
        public string AcctComments { get; set; }
        public Nullable<int> ItContactId { get; set; }
        public Nullable<int> CSContactId { get; set; }
        public Nullable<int> AcctContactId { get; set; }
    }
}
