//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse_Lookup
    {
        public WareHouse_Lookup()
        {
            this.ItemWareHouses = new HashSet<ItemWareHous>();
        }
    
        public int WareHouse_id { get; set; }
        public string WareHouseNumber { get; set; }
        public string WareHouseName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<ItemWareHous> ItemWareHouses { get; set; }
    }
}
