//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class zManufacturersLogo
    {
        public zManufacturersLogo()
        {
            this.Items = new HashSet<Item>();
            this.zManufacturersLogo_History = new HashSet<zManufacturersLogo_History>();
        }
    
        public int ManufacturerLogo_Id { get; set; }
        public string VendorNumber { get; set; }
        public string APlusVendorName { get; set; }
        public string LogoName { get; set; }
        public string WebVendorName { get; set; }
        public string Abbrev { get; set; }
        public string URL { get; set; }
        public Nullable<int> Buyer_Id { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<zManufacturersLogo_History> zManufacturersLogo_History { get; set; }
    }
}
