//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class zManufacturersLogo_History
    {
        public int ManufacturerLogoHistory_Id { get; set; }
        public int ManufacturerLogo_Id { get; set; }
        public string VendorNumber { get; set; }
        public string APlusVendorName_Original { get; set; }
        public string LogoName_Original { get; set; }
        public string WebVendorName_Original { get; set; }
        public string Abbrev_Original { get; set; }
        public string APlusVendorName_New { get; set; }
        public string LogoName_New { get; set; }
        public string WebVendorName_New { get; set; }
        public string Abbrev_New { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string URL_Original { get; set; }
        public string URL_New { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual zManufacturersLogo zManufacturersLogo { get; set; }
    }
}
